### ISSUE TITLE
compute_ann_mean does not work if time is encoded

### ISSUE THREAD

**Issue by klindsay28** [NCAR/esmlab#93]
I'm calling `ds_ann = compute_ann_mean(ds)` on an xarray Dataset with `ds.time` is encoded, and it fails down in xarray.

The python code in the following file, which has a .txt suffix to enable me to attach it, exhibits the problem:
[esmlab_compute_ann_mean_time_encoded.py.txt](https://github.com/NCAR/esmlab/files/2954484/esmlab_compute_ann_mean_time_encoded.py.txt)

The python creates an example Dataset that has time encoded. It accomplishes this by first creating an Dataset with time unencoded, writes that to a netcdf file, and reads it back in with xr.open_mfdataset. The script then calls `ds_ann = compute_ann_means(ds)` on the result, and I get the following error.

> Traceback (most recent call last):
  File "esmlab_compute_ann_mean_time_encoded.py", line 33, in <module>
    ds_ann = esmlab.climatology.compute_ann_mean(ds)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/gpfs/fs1/work/klindsay/analysis/esmlab/esmlab/climatology.py", line 178, in compute_ann_mean
    dset = tm.compute_time()
  File "/gpfs/fs1/work/klindsay/analysis/esmlab/esmlab/utils/time.py", line 173, in compute_time
    if self.time_bound is not None:
  File "/gpfs/fs1/work/klindsay/analysis/esmlab/esmlab/utils/time.py", line 216, in time_bound
    return xr.DataArray(tb_value, dims=(self.time_coord_name))
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.6/site-packages/xarray/core/dataarray.py", line 230, in __init__
    variable = Variable(dims, data, attrs, encoding, fastpath=True)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.6/site-packages/xarray/core/variable.py", line 260, in __init__
    self._dims = self._parse_dimensions(dims)
  File "/glade/work/klindsay/miniconda3/envs/analysis/lib/python3.6/site-packages/xarray/core/variable.py", line 424, in _parse_dimensions
    % (dims, self.ndim))
ValueError: dimensions ('time',) must have the same length as the number of data dimensions, ndim=2

I am using the trunk of esmlab. conda list returns the following for xarray, numpy, and esmlab:

> esmlab                    2019.2.0+30.ged53a19           dev_0    <develop>
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
xarray                    0.11.3                   pypi_0    pypi

This worked with versions of esmlab prior to:
> commit a61c79adcc5291d32b571faab3203c601da08e8c
Author: mclong <mclong@ucar.edu>
Date:   Thu Feb 21 20:42:52 2019 -0700

    time_manager: returns ds with original time

**Comment by andersy005** [comment]
Fixed in #98, #100. 

@klindsay28 feel free to reopen this issue if the problem persists.
